### ISSUE TITLE
How to handle dynamic delay ranging from 50-2000 milli seconds 

### ISSUE THREAD

**Issue by Aijaz98** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#103]
### Subject of the issue
I am using ICM-20948 IMU sensor with an example of DMP_Quat6_Euler angles, 

### Your workbench
* What platform are you using?
* What version of the device are you using? Is there a firmware version?
* How is the device wired to your platform?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by PaulZC** [comment]
Closing in favour of #104
