### ISSUE TITLE
How Full Scale is set when DMP enabled?

### ISSUE THREAD

**Issue by techtoys** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#107]
### Subject of the issue
Can't set full scale when DMP is enabled in Example 8_DMP_RawAccel.ino

### Your workbench
* ESP32-PICO-D4
* SparkFun 9DoF IMU version 1.2.9
* I2C - 400kHz

### Steps to reproduce
Setup section:
```
void setup()
{
 SERIAL_PORT.begin(115200); // Start the serial console
 SERIAL_PORT.println(F("ICM-20948 Example"));
//...skip for simplicity
success &= (myICM.enableDMPSensor(INV_ICM20948_SENSOR_ACCELEROMETER) == ICM_20948_Stat_Ok);
success &= (myICM.enableFIFO() == ICM_20948_Stat_Ok);
success &= (myICM.enableDMP() == ICM_20948_Stat_Ok);
//now I want to lift the FS
ICM_20948_fss_t myFSS; // This uses a "Full Scale Settings" structure that can contain values for all configurable sensors
  myFSS.a = gpm8; // (ICM_20948_ACCEL_CONFIG_FS_SEL_e)
                  // gpm2
                  // gpm4
                  // gpm8
                  // gpm16

  myFSS.g = dps2000; // (ICM_20948_GYRO_CONFIG_1_FS_SEL_e)
                    // dps250
                    // dps500
                    // dps1000
                    // dps2000

  myICM.setFullScale((ICM_20948_Internal_Acc | ICM_20948_Internal_Gyr), myFSS);
}
```
Code snippet below shows the section I am looking in Serial Plot.
```
    if ((data.header & DMP_header_bitmap_Accel) > 0) // Check the packet contains Accel data
    {
      float acc_x = (float)data.Raw_Accel.Data.X; // Extract the raw accelerometer data
      float acc_y = (float)data.Raw_Accel.Data.Y;
      float acc_z = (float)data.Raw_Accel.Data.Z;

      SERIAL_PORT.print(F("X:"));
      SERIAL_PORT.print(acc_x);
      SERIAL_PORT.print(F(" Y:"));
      SERIAL_PORT.print(acc_y);
      SERIAL_PORT.print(F(" Z:"));
      SERIAL_PORT.println(acc_z);
    }
```

### Expected behaviour
I expected the full scale of Acc will be lifted to +/-8g

### Actual behaviour
Before the modification was made, the full scale was +/-4g with a clear overflow at 4g when I twitched the sensor in Y direction. I think +/-4g is the default in the driver.
After the change with new `myFSS.a = gpm8` I expected the full scale would be lifted to 8g but still the plateau stayed the same at 4g.

**Comment by PaulZC** [comment]
Hi @techtoys ,

You also need to change the DMP ```ACC_SCALE``` and ```ACC_SCALE2```. Those are set in ```initializeDMP``` but you can set them manually too. Please see these lines in Example10 - which defines a 'custom' version of ```initializeDMP```:

https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/fd948fbc5dbe080eddafe88e3c1f7eadf5baff69/examples/Arduino/Example10_DMP_FastMultipleSensors/Example10_DMP_FastMultipleSensors.ino#L400-L407

I'm closing this as I believe this will correct your issue. Please re-open if you need more help.

Best wishes,
Paul
