### ISSUE TITLE
USING DMP 9 axis DOF，angle cannot stop immediately

### ISSUE THREAD

**Issue by muniye** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#118]
I used icm20948 DMP 9 AXIS DOF to output attitude Angle datas. The magnetometer was calibrated well through 8-figure calibration, and the data response was good. However, when the sensor stops after motion, the Angle does not stop immediately, and the Angle data still takes 0.5 to 3 seconds to stop. (It seems like  calibrating).The more intense the exercise, the more obvious the phenomenon.I did not have this problem when I used icm20948 DMP 6 AXIS DOF.  Because I use icm20948 as a mouse, this problem is unbearable.

**Comment by PaulZC** [comment]
Hello @muniye ,

I am sorry. I do not have an answer for you. There are many things about the DMP that we do not understand. If you look through the open and closed issues, you will long discussions about the behaviour and performance of the DMP.

Very best wishes,
Paul

**Comment by muniye** [comment]
OK,Thank you for your response.
