### ISSUE TITLE
two interrupt

### ISSUE THREAD

**Issue by JacksonLtt** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#119]
How could I control two icm20948 both using interrupt with same i2c bus?

**Comment by PaulZC** [comment]
Hello Taiting (@JacksonLtt ),

It should be as simple as:

```
ICM_20948_I2C myICM0;
ICM_20948_I2C myICM1;

void setup()
{
  Wire.begin();
  myICM0.begin(Wire, 0);
  myICM1.begin(Wire, 1);
```

But I am not sure how you want to use interrupts? Please explain a little more.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Closing. Please reopen if you need more help with this.
