### ISSUE TITLE
What is the meaning of the accuracy value in the Quat9 example?

### ISSUE THREAD

**Issue by joshgalvan** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#125]
Hello!

I'm unable to find anything in the documentation for what this accuracy represents. I've read the other open issue on accuracy, but it is more referring to the raw accel/gyro/mag accuracy, which should be 0-3. The 0-3 is fine and I understand that 3 means it's most accurate.

[Here](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/issues/34#issuecomment-836367024), though, @PaulZC says that the accuracy from the Quat9 example (`data.Quat9.Data.Accuracy`) is the compass accuracy, but what is the interpretation of this number? The number is `uint16_t` and for me floats around 300 or so.

Thanks.

**Comment by PaulZC** [comment]
Hi Joshua,

Apologies for the very slow reply. I missed this one...

The only information I have is: "The accuracy is expressed as 0~3. The lowest is 0 and 3 is the highest.".

Best wishes,
Paul
