### ISSUE TITLE
Found solution for: SparkFun ICU-29048 does not initialize. Serial monitor displays "Data Underflow"

### ISSUE THREAD

**Issue by dfr2248** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#128]
###SparkFun ICU-20948
Found Solution for "Data Underflow"

### Your workbench
* Using RedBoard Plus and RedBoard Artemis
Connected using Qwiic connectors.
* Powered by RedBoard Plus or RedBoard Artemis

### Steps to reproduce
Running any sketch, the sketch compiles without errors, but when the Serial Monitor is activated it reads "Data Underflow"
Normally all the data should be displayed, but it is not.

### Actual behaviour
reads "Data Underflow" in the Serial Monitor 

The ADR jumper on the back of the board is soldered which make the AD0_VAL 0. In the sketch "Example1_Basic, line 24 reads AD0_VAL 1. Change line 24 to AD0_VAL 0. Compile the sketch, open the Serial Monitor , and the data will be displayed. I believe this is the fix for all the Example Sketches.

**Comment by PaulZC** [comment]
Hi @dfr2248 ,

Yes, closing the ADR jumper changes the I2C address from 0x69 (AD1) to 0x68 (AD0). Closing the ADR jumper prevents you from using the SPI interface, so - on SparkFun boards - we ship them with the jumper open. The examples are correct for the SparkFun board as shipped.

![image](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/assets/5690545/8ce84816-090a-4fd3-8e26-744a4dadacfe)

I am glad you found the solution.

Best wishes,
Paul
