### ISSUE TITLE
IMU Calibration

### ISSUE THREAD

**Issue by Amirhosein80** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#138]
Hello, I have some questions about IMU Calibration for quaternions.
1. How do I calibrate IMU?
2. How can I check the accuracy of the IMU calibration?

I would appreciate any insights or documentation you could provide on these matters.
Thank you!

**Comment by PaulZC** [comment]
Hi @Amirhosein80 ,

Please search the open and closed issues. Many of them are relevant to DMP (IMU) calibration.

https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/issues?q=is%3Aissue+is%3Aclosed+calibrate+rotate

Best wishes,
Paul
