### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by waqasqammar** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#14]
### Subject of the issue
Calibration needed?

### Your workbench
I want to ask if the calibration is needed if we are using C code or C++ code? if it is needed then how we can add that automatically in the code?

**Comment by oclyke** [comment]
Whether or not calibration is needed depends on your use case. It is possible to use values from the sensor without any calibration as long as that is acceptable for you. If you need calibration then you will need to decide what method to use and them implement it in code. 

For example one way to calibrate would be to make sure that when the sensor is flat (or when the robot it is being used in is in resting postion, for example) and stationary that the acceleration values equate to [0, 0, 1g] exactly. You could have a button or command that automatically corrects by taking readings (avg. would be good) and then storing the offset. All subsequent readings could have the offset subtracted. This is just one of many possible calibration schemes. Another common calibration is to make sure that the magnitude of the measured magnetic field is the same in all orientations (used to correct for the physical structure enclosing the IMU typically). I would suggest reading more into IMU calibration and consider the particular needs of your project.

You may also search the [datasheet](https://invensense.tdk.com/wp-content/uploads/2016/06/DS-000189-ICM-20948-v1.3.pdf) for 'calibrate' and 'calibration' for more information. DMP features are not supported by this library as mentioned in #1
