### ISSUE TITLE
swreset and DMP

### ISSUE THREAD

**Issue by Gonta01** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#140]
### Subject of the issue
Hi. Why swReset() function is called in Example2_Advanced.ino Example3_Interrupts.ino  and Example4_WakeOnMotion.ino but not in  Example9_DMP_MultipleSensors.ino (and other DMP related examples)?
Is it because of special DMP configuration? Could it somehow affect it's behavior?

**Comment by PaulZC** [comment]
Hi @Gonta01 ,

The DMP is loaded into the ICM20948's internal memory. A software reset will (probably) clear it.

Best wishes,
Paul
