### ISSUE TITLE
Compass and rotation 

### ISSUE THREAD

**Issue by minhanh1234** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#142]
Hi

Would you know if this chip can calculate compass angle like most magnetometer and would you have any example code to calculate rotation count? Example if i rotate the gyro on a table? (Example: 2 counter clockwise ration)

Thanks

**Comment by PaulZC** [comment]
Hi Minh (@minhanh1234 ),

You can calculate approximate angle from either the raw magnetometer readings or the DMP quaternions. Please see the [examples](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/main/examples/Arduino/Example7_DMP_Quat6_EulerAngles/Example7_DMP_Quat6_EulerAngles.ino) for more details.

The DMP has no built-in support for rotation counting. You will need to add your own.

Best wishes,
Paul
