### ISSUE TITLE
Heading alignment with gyro and gnss without dmp

### ISSUE THREAD

**Issue by jasvinder1079** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#144]
Hello @PaulZC,

Thank you for recommending the IM19 IMU for high precision accuracy. However, I have a doubt: can we achieve the same level of accuracy with the ICM-20948? For my application, frequent calibration and drift in magnetometer values are not acceptable. How can we obtain the heading alignment value using only gyro and GNSS data? I have reviewed many research papers, but nothing has worked for me so far.

Thank you for your assistance.

**Comment by PaulZC** [comment]
Hello Jasvinder (@jasvinder1079 ),

I am sorry, I do not know if the 20948 DMP is suitable for this. You will need to test it yourself. The sensors will drift over time and with temperature.

Best wishes,
Paul
