### ISSUE TITLE
Compass Alignment with Roll and Pitch Axes (DMP)

### ISSUE THREAD

**Issue by Gord1** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#145]
### Subject of the issue
I'm finding that the Compass (yaw) is 90 deg off from what I'm expecting with respect to the roll and pitch directions.

I'm using SparkFun Example11_DMP_Bias_Save_Restore_ESP32 that I have modified slightly for the ESP8266.  This example takes the quaternion data and calculates roll, pitch and yaw.  The angles are all good, except for the zero reference for the yaw angle.  That seems to be rotated 90 deg.

If I set the board flat with 0 yaw, the "nose" of the board will point north.  If I lift the nose up I would expect the pitch angle to change, but the roll changes.

issue #114 @texasfunambule may have made a comment about this > The quat9 example seems to work fine (except maybe for compass alignement)

Could the quaternion components be mixed in the roll, pitch, yaw equations??  That is beyond my pay grade.

**Comment by PaulZC** [comment]
Hi @Gord1 ,

Welcome to the weird and wonderful world of the ICM20948 DMP!

Agreed. I'm seeing the same thing. Looks like I've got a rotation in there.

My setup: SparkFun ESP32 Thing Plus C, connected to a SparkFun ICM-20948 breakout via I2C; Arduino IDE 1.8.19; Espressif ESP32 boards 3.0.1.

If I let Example11 run for a while, do the three rotations and six holds, the Yaw reports 0 degrees when the Accel/Gyro Y axis is pointing towards magnetic North. But, yes, roll and pitch are reversed. Also, Yaw goes negative when I rotate clockwise from North.

IIRC, I used the conversion code from here (or a very similar source):

https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Source_code_2

In the example code, I assumed Q0/1/2/3 mapped onto Qw/x/y/z. That appears to be untrue...

I don't have time to dig into this right now. I will try and get to it ~soon. If you have time and can correct the sequence, please do and send us a Pull Request.

Best wishes,
Paul

**Comment by Gord1** [comment]
> 
> Agreed. I'm seeing the same thing. Looks like I've got a rotation in there.
> 
Hi @PaulZC 

Many thanks for looking into this and confirming the issue.

> In the example code, I assumed Q0/1/2/3 mapped onto Qw/x/y/z. That appears to be untrue...

The coordinate frame for the accelerometer and gyro are different than the magnetometer on the  ICM20948.  Do you have any information on the coordinate frame for the DMP and how it relates to the physical chip?

There are a lot of combinations to start trying them randomly shooting in the dark.

Thanks,
Gord

**Comment by Gord1** [comment]
Hi @PaulZC,

In the example 11 code the 4th quaternion is calculated by
double q0 = sqrt(1.0 - ((q1 * q1) + (q2 * q2) + (q3 * q3)));

This is always taken as positive while it could be +/- as it is the square root.  Depending on whether you take the positive q0 or negative, don't you get a different rotation?

Regards,
Gord

**Comment by Gord1** [comment]
![Screenshot 2024-08-13 at 17-10-45 DS-000189-ICM-20948-v1 6 pdf](https://github.com/user-attachments/assets/5b8b29e0-f3e2-4c49-aaec-2a29e02163d1)

This seems to be the directions for both the Gyro and the Quaternion.

If I tilt the board around the x-axis both the gx and q1 increase for +ve rotation.  The same for the y and z axis.

For the roll, pitch, yaw calculation equations in example 11, I'm guessing that the x-axis is defined as forward and not the y-axis as shown above.

I'm not familiar with quats.  I guess we should we switching q1,q2 and q3 around.

Gord

**Comment by Gord1** [comment]
Hi @PaulZC,

Here is the bit of code to swap the axis around so they work with the equations that are in standard aircraft dynamics form:


			// Scale to +/- 1
			//  -GW note The ICM 20948 chip has axes y-forward, x-right and Z-up
			//  -see Figure 12. Orientation of Axes of Sensitivity and Polarity of Rotation
			//	DS-000189-ICM-20948-v1.6.pdf  These are the axes for gyro and accel and quat
			//
			//  For conversion to roll, pitch and yaw for the equations below, the coordinate frame
			//  must be in aircraft reference frame.
			//  
			// we use the Tait Bryan angles (in terms of flight dynamics):
			// ref: https://en.wikipedia.org/w/index.php?title=Conversion_between_quaternions_and_Euler_angles
			//
			// Heading – ψ : rotation about the Z-axis (+/- 180 deg.)
			// Pitch – θ : rotation about the new Y-axis (+/- 90 deg.)
			// Bank – ϕ : rotation about the new X-axis  (+/- 180 deg.)
			//
			// where the X-axis points forward (pin 1 on chip), Y-axis to the right and Z-axis downward.
			// In the conversion example above the rotation occurs in the order heading, pitch, bank. 
			// To get the roll, pitch and yaw equations to work properly we need to exchange the axes
			
			// Note when pitch approaches +/- 90 deg. the heading and bank become less meaningfull because the
			// device is pointing up/down.

			double qx, qy;  // some temp vars for switching axis

			qx = q1;
			qy = q2;

			// w no change
			q1= qy;  //x and y exchanged
			q2= qx;
			q3= -q3; //neg z

Now do conversion ...

Regards,
Gord

**Comment by PaulZC** [comment]
Hi Gord (@Gord1 ),

Thank you.

I went with the following, to avoid messing up the QUAT_ANIMATION:

https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/168c18b8ebf7c8a28ac22f1351f23e0f143ba195/examples/Arduino/Example11_DMP_Bias_Save_Restore_ESP32/Example11_DMP_Bias_Save_Restore_ESP32.ino#L346-L367

I'll release these changes in a few minutes.

Thanks again,
Paul

**Comment by PaulZC** [comment]
Resolved by https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/releases/tag/v1.2.13

**Comment by minamulhaq** [comment]
DMP official driver has this function to poll sensor

```c
int inv_icm20948_poll_sensor(struct inv_icm20948 *s, void *context,
			     void (*handler)(void *context,
					     enum inv_icm20948_sensor sensor,
					     uint64_t timestamp,
					     const void *data, const void *arg))
```

if I read data from this function, I get weird yaw follwoing the setup used by (https://github.com/ZaneL/Teensy-ICM-20948/blob/e0cc6c04f23eb04e199b27180b3038664f17f692/src/Teensy-ICM-20948.cpp#L244)

```c
void GetEulerAngles(const float quat[4], double *yaw, double *pitch,
		    double *roll, double *norm)
{
	float q0 = quat[0];
	float q1 = quat[1];
	float q2 = quat[2];
	float q3 = quat[3];

	*norm = sqrtf(q0 * q0 + q1 * q1 + q2 * q2 + q3 * q3);

	q0 /= *norm;
	q1 /= *norm;
	q2 /= *norm;
	q3 /= *norm;

	double r11 = q0 * q0 + q1 * q1 - q2 * q2 - q3 * q3;
	double r12 = 2 * (q1 * q2 + q0 * q3);
	double r13 = 2 * (q1 * q3 - q0 * q2);
	double r23 = 2 * (q2 * q3 + q0 * q1);
	double r33 = q0 * q0 - q1 * q1 - q2 * q2 + q3 * q3;

	*roll = atan2(r23, r33) * RAD_TO_DEG;
	*pitch = -asinf(r13) * RAD_TO_DEG;
	*yaw = atan2(r12, r11) * RAD_TO_DEG;
	printf("%2.2f [%2.2f, %2.2f, %2.2f, %2.2f] | R:%5.2f | P:%5.2f | Y:%5.2f\n",
	       *norm, q0, q1, q2, q3, *roll, *pitch, *yaw);
}

```

This is my implementation where I am printing norm, quaternion and euler angles, 

Observation:

1. If I apply positive yaw, I get correct angles 
1.00 [1.00, 0.01, 0.00, 0.01] | R: 1.12 | P: 0.38 | Y: 1.25
1.00 [1.00, 0.01, 0.00, 0.09] | R: 0.98 | P: 0.36 | Y:10.50
1.00 [0.98, 0.01, 0.01, 0.18] | R: 1.60 | P: 0.43 | Y:20.79
1.00 [0.96, 0.01, 0.00, 0.27] | R: 1.17 | P: 0.24 | Y:30.96


2. If I apply negative yaw and cross 0, 
4.12 [0.25, 0.00, 0.00, 0.97] | R: 0.14 | P:-0.19 | Y:151.09
4.12 [0.34, 0.00, 0.00, 0.94] | R: 0.14 | P:-0.16 | Y:140.24

3. The norm increases to large value (e.g > 4, 5) 

Required behavior:
As I am expecting negative rotation, yaw should be -ive like -5 degrees, -10 degrees and roll and pitch should remain same, 
is it rolling over or something wrong in my setup?
