### ISSUE TITLE
Incorrect temperature formula

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#17]
Hi,

During a recent investigation as to why the ICM-20948 temperature readings are about 5°C higher than other sensors (turns out the die temperature just runs hotter), I discovered a small error in the temperature formula used in this library.

https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/4d5f843753ec01c0c16484c97b6d7b6e459d260d/src/ICM_20948.cpp#L123-L126

According to the ICM-20948 the datasheet, it appears the above formula is missing the RoomTemp_Offset.
![image](https://user-images.githubusercontent.com/22924092/90980160-b4eae680-e527-11ea-8c7d-4c73eb52eabb.png)

I believe the formula should end up looking something like:
```C
 float ICM_20948::getTempC(int16_t val) 
 { 
     return (((float)val - 21) / 333.87) + 21; 
 }
```

Cheers,
Adam

**Comment by adamgarbo** [comment]
Address by PR #18.

**Comment by Gonta01** [comment]
Hi. It seems to me that formula was correct. According to ICM-20948 datasheet:
![image](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/assets/127857320/5462803b-636e-41b4-a9f4-2a06b7ad6eb4)
Room Temp offset is 0. Condition: 21°C
Isn't it?

**Comment by adamgarbo** [comment]
Yup! I think you're right.
