### ISSUE TITLE
Accelerometer Raw Values at rest horizontal position gives 1 unit shift values

### ISSUE THREAD

**Issue by shubhangiingle** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#33]
I want to calculate gravity values at rest horizontal position. Ideally for 2g sensitivity , it should give me raw values around 16500 but it gives me values around 14000 for positive z axis and 17000 for negative z axis. Which eventually makes calculation 8.8m/s2 and 10m/s2 respectively. What should be reason for such higher and lower raw values ? What is solution to this problem ?

**Comment by PaulZC** [comment]
Hi @shubhangiingle ,
It's just sensor offset and gain. You'll need to calibrate the sensor and apply the offset to center the signal. Maybe adjust the gain slightly too.
Best wishes,
Paul
