### ISSUE TITLE
Duplicate Declaration of ICM_20948_get_agmt() in ICM_20948_C.h

### ISSUE THREAD

**Issue by Arnatious** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#48]
https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/c5a699b98aaddfd119e821c941978834722e9910/src/util/ICM_20948_C.h#L217-L219

Appears to have been duplicated by whitespace fixes in ed6edf6d30f137e86b2c612b93d6968b68c7ae55.

**Comment by PaulZC** [comment]
Woah! How did that get in there!?
Thank you Ted (@Arnatious ) - fixed in [1.2.4](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/releases/tag/v1.2.4)
