### ISSUE TITLE
Paid Support

### ISSUE THREAD

**Issue by nsmith1024** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#54]
### Subject of the issue
Im making a project that automatically points a camera to a star, moon, planet, galaxy etc.

It gets the coordinates of the desired star or moon etc from stellarium (open source astronomy program), and then its supposed to use the ICM-29048 (attached to the camera) and little motors to move the camera until it points to the proper coordinates using positional feedback from the ICM-20948.

I was willing to pay someone to help me get that working using Arduino since i dont have time to do it all myself.

Please contact me at iosdev1024@yahoo.com if you are interested, and let me know your price.

**Comment by PaulZC** [comment]
Hi @nsmith1024 ,
The best place to ask for help would be on the [IMU forum](https://forum.sparkfun.com/viewforum.php?f=83).
Best wishes,
Paul
