### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#80]
In the file "examples/PortableC/Example999_Portable/Example999_Portable.ino" there is a Wire.endTransmission() after a Wire.requestFrom(). That Wire.endTransmission() is currently at line 205 and should be removed.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by PaulZC** [comment]
Many thanks @Koepel ,
Corrected in [this commit](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/commit/5ee49bcdf155a439f1184d2fcda1f6ffe51f9af7). The change will be included in the next release.
Best wishes,
Paul
