### ISSUE TITLE
Magnetometer not enabled/working through DMP quaternions?

### ISSUE THREAD

**Issue by dewmgaze** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#81]
### Subject of the issue
Tested using INV_ICM20948_SENSOR_ROTATION_VECTOR, INV_ICM20948_SENSOR_GEOMAGNETIC_ROTATION_VECTOR, and INV_ICM20948_SENSOR_ORIENTATION
Quaternions I get back from DMP_header_bitmap_Quat9 are fine to generate roll and pitch, even yaw works fine, it's just yaw has no magnetic attachment. I've watched the quaternions as I take a neodymium magnet and move it near and around the sensor with no change in value.

I've logged the raw magnetometer values from agmt, and those values actually do seem to respond to the magnet, although magX is a little strange in that the value of agmt.mag.axes.x is usually  -256, and doesn't change subtly with movement but rather will jump to 0 or other specific values after extreme movement or, with a magnet moved nearby.

### Your workbench
ESP32 using i2c to connect
Building on platformIO
Power from ESP's usb port from PC

### Steps to reproduce
Quat9 example sketch, just swap INV_ICM20948_SENSOR_ORIENTATION for any of the other values, and observe that a magnet has no affect on quaternion output from DMP

### Expected behaviour
Quaternions change in relation to magnet fields

### Actual behaviour
Quaternions have no magnetic basis, effectively Quat9 is the same as Quat6

**Comment by dewmgaze** [comment]
Whoops, should have included that. 1.2.7, I've read through some of the DMP issues on versions prior, like the low power thing.

	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library @ ^1.2.7

**Comment by dewmgaze** [comment]
Running example6 DMP quat 9, with a few lines added to calculate orientation from the quaternions, I'm getting good roll/pitch but yaw starts at 300 on reset, and drifts to 215-250. A quick turn will give the expected change in yaw, but then it drifts back to the 215-250 range.  Placing a magnet near the board causes no change to the yaw.

**Comment by PaulZC** [comment]
Hi @dewmgaze ,

I've been thinking more about this. I suspect that when you move your magnet - and do not move the IMU - the DMP may be clever enough to know that the IMU is not moving (from the accelerometers and gyros) and so produces no change in the orientation.

I am going to close this issue as I do not think I can give you any more help or advice. Please re-open if you still suspect a configuration problem with the DMP and can point me towards it.

Very best wishes,
Paul
