### ISSUE TITLE
Reference to DMP and how to Enable PedoMeter

### ISSUE THREAD

**Issue by AhmedNabih** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#82]
I am Tring to enable the pedometer to count my steps, with no success.
Can you help?

**Comment by PaulZC** [comment]
Hi @AhmedNabih ,

Yes, we are aware of this (please see #75) and we don't have a fix for it right now.

It will involve going back through the InvenSense example code (which is _very_ opaque) and reverse-engineering how they configure the DMP for step counting. It is not an easy thing to do and unfortunately we do not have time to do it right now.

I am going to close this in favor of #75.

Very best wishes,
Paul
