### ISSUE TITLE
Compilation error for Arduino Uno board

### ISSUE THREAD

**Issue by rperezdomi** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#89]
Hi Paul,

I have tried unsuccessfully to load your code "Example7_DMP_Quat6_EulerAngles.ino" on an Arduino uno board.

Everything goes well until I uncomment the line 29 in "ICM_20948_C.h" (as it appears specified in the code to enable DMP). Is then when I get a compilation error due to a high program storage space usage. Could you please let mi know how can I solve this error?

![imagen](https://user-images.githubusercontent.com/78550162/148975007-27d9d3d7-4503-417d-a3e7-e404c3c83bcc.png)

In addition, I have a question about the use of DMP as I don't quite understand how it works. If it is suppose to offload computation of motion processing algorithms from the host processor, Why does it takes up so much storage space on it?

Thank you in advance,
Raquel.

**Comment by PaulZC** [comment]
Hi Raquel,

Please see the comment here:

https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/main/DMP.md#is-dmp-support-enabled-by-default

The Uno (ATmega328P) only has 32kBytes of program memory. That's not enough to hold all of the library code plus the DMP firmware (14kBytes). Together they come to about 35kBytes.

The DMP software / firmware needs to be downloaded onto the ICM20948. It needs to be stored somewhere, and the simplest solution is to include it in the library source code so it is stored in the processor's program memory.

There may be a way to (e.g.) store the DMP firmware on microSD card and download it from there onto the ICM20948, without needing to store it in the ATmega's memory. But that would take quite a lot of effort.

My advice is to buy a board with more memory. Sorry!

Best wishes,
Paul
