### ISSUE TITLE
Does the I2C master and compass ODR need to be set to 68.75Hz or is the accuracy better when it matches the gyro/accel ODR, potentially higher than compass ODR, e.g. 225Hz?

### ISSUE THREAD

**Issue by msrivast** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#93]
Not an issue - just a question.

**Comment by PaulZC** [comment]
Hi @msrivast ,

Honest answer: I don't know! I've included a lot of notes here which should help:

https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/d5ae1eba1ecbf808fca9bff0b0b6dc4e571e947c/examples/Arduino/Example10_DMP_FastMultipleSensors/Example10_DMP_FastMultipleSensors.ino#L264-L310

Best wishes,
Paul
