### ISSUE TITLE
Difference between Sparkfun and ZaneL's wrapper? 

### ISSUE THREAD

**Issue by msrivast** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#94]
I know of a few and would like to make sure I understand correctly.
 - Zane's library does not support I2C
 - Zane's library does not support magnetometer/compass

Please add anything else that I may have missed.

Cheers,
Manu

**Comment by PaulZC** [comment]
Hi Manu (@msrivast ),

"Zane's library does not support" is not really the right way to think about this. It is more correct to say "Zane does not provide an example of how to use I2C and magnetometer/compass".

Zane's excellent wrapper is just that: a wrapper for the InvenSense example code. With the SparkFun library, we tried to fully understand the DMP and provide documented code and examples that others could follow and re-use. It was a huge challenge and the work is not complete... Have a look at [DMP.md](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/main/DMP.md) and have a read through the open and closed issues re. the DMP.

Best wishes,
Paul
