### ISSUE TITLE
Lesser than expected time period between FIFO new data

### ISSUE THREAD

**Issue by msrivast** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#95]
Hi @PaulZC  and thanks again for this splendid library!

1. I am using example 10 with acc/gyro ODR at 225hz, compass at 68.75hz and setting the DMP ODR rate to 25hz so that sensor fusion can happen at a fast rate. I modified the example slightly to calculate the time difference between sample and to convert quaternions to Euler angles. At 25hz, I should get samples 40ms apart. In the output below, the number on the left indicates the zero normalized value of the time difference in ms(current_time - previous_time - 40). I notice that a lot of samples arrive 1 sometimes 2 ms before time and very few arrive late. I know that the PLL can vary but is this the expected behaviour? I did not see any compensation using TIMEBASE_CORRECTION_PLL register in the library. 

2. I saw spikes in the DMP o/p when using DMP ODR 225hz. Those spikes go away at DMP ODR 25hz. I am assuming that the DMP has some kind of moving average calculation. Do you have anything more to share about this?

3. I know that the acc/gyro sample rate max is 1125hz according to the datasheet. When we get data at a slower rate using SMPLRT_DIV registers, are those sensors averaging the data generated at 1125hz or do they not generate any data for a few clock pulses in the middle? In the data sheet, Table 17 talks about the gyroscope averaging data in the low power mode but I am 99% certain, we aren't operating these sensors in the low power mode. Any thoughts on this and the above are appreciated! 

Cheers,
Manu

p.s. I am using ESP32 to do the timing, library version 1.2.9 and using I2C. I am polling the DMP and not using interrupts.

0 Roll:-170 Pitch:-63 Yaw:163
0 Roll:-169 Pitch:-64 Yaw:164
-1 Roll:-168 Pitch:-64 Yaw:167
0 Roll:-166 Pitch:-65 Yaw:169
0 Roll:-165 Pitch:-66 Yaw:171
-1 Roll:-164 Pitch:-67 Yaw:173
0 Roll:-163 Pitch:-68 Yaw:176
-1 Roll:-162 Pitch:-68 Yaw:178
0 Roll:-161 Pitch:-69 Yaw:-180
0 Roll:-160 Pitch:-70 Yaw:-178
-1 Roll:-160 Pitch:-69 Yaw:-175
0 Roll:-159 Pitch:-70 Yaw:-174
0 Roll:-159 Pitch:-70 Yaw:-172
-1 Roll:-159 Pitch:-70 Yaw:-170
0 Roll:-160 Pitch:-70 Yaw:-167
-1 Roll:-160 Pitch:-70 Yaw:-165
0 Roll:-162 Pitch:-70 Yaw:-162
1 Roll:-162 Pitch:-71 Yaw:-160
-2 Roll:-162 Pitch:-71 Yaw:-158
0 Roll:-162 Pitch:-72 Yaw:-157
0 Roll:-162 Pitch:-73 Yaw:-154
-1 Roll:-162 Pitch:-73 Yaw:-152
0 Roll:-162 Pitch:-74 Yaw:-151
0 Roll:-160 Pitch:-75 Yaw:-153
-1 Roll:-158 Pitch:-77 Yaw:-155
0 Roll:-154 Pitch:-79 Yaw:-159
-1 Roll:-149 Pitch:-81 Yaw:-165
0 Roll:-142 Pitch:-83 Yaw:-173
0 Roll:-126 Pitch:-85 Yaw:170
-1 Roll:-83 Pitch:-86 Yaw:127
0 Roll:-61 Pitch:-85 Yaw:105
0 Roll:-49 Pitch:-84 Yaw:93
-1 Roll:-33 Pitch:-81 Yaw:77
0 Roll:-25 Pitch:-77 Yaw:68
-1 Roll:-19 Pitch:-72 Yaw:61
0 Roll:-16 Pitch:-67 Yaw:56
0 Roll:-13 Pitch:-62 Yaw:52
-1 Roll:-11 Pitch:-56 Yaw:48
0 Roll:-11 Pitch:-51 Yaw:47
0 Roll:-11 Pitch:-46 Yaw:46
-1 Roll:-11 Pitch:-41 Yaw:46
0 Roll:-11 Pitch:-37 Yaw:46
-1 Roll:-10 Pitch:-32 Yaw:46
0 Roll:-9 Pitch:-26 Yaw:44
0 Roll:-8 Pitch:-19 Yaw:43
-1 Roll:-7 Pitch:-13 Yaw:41
0 Roll:-6 Pitch:-7 Yaw:41
0 Roll:-5 Pitch:-0 Yaw:41
-1 Roll:-5 Pitch:6 Yaw:41
1 Roll:-6 Pitch:10 Yaw:42
-2 Roll:-8 Pitch:16 Yaw:41
0 Roll:-9 Pitch:20 Yaw:39
0 Roll:-11 Pitch:24 Yaw:39
-1 Roll:-13 Pitch:27 Yaw:37
1 Roll:-13 Pitch:29 Yaw:38
-1 Roll:-14 Pitch:32 Yaw:38
-1 Roll:-15 Pitch:35 Yaw:37
0 Roll:-15 Pitch:38 Yaw:38
-1 Roll:-16 Pitch:42 Yaw:37
0 Roll:-16 Pitch:44 Yaw:37
1 Roll:-16 Pitch:47 Yaw:37
-2 Roll:-17 Pitch:50 Yaw:36
0 Roll:-18 Pitch:53 Yaw:34
0 Roll:-19 Pitch:56 Yaw:34
-1 Roll:-20 Pitch:59 Yaw:33
0 Roll:-19 Pitch:61 Yaw:34
-1 Roll:-18 Pitch:64 Yaw:35
0 Roll:-17 Pitch:66 Yaw:36
0 Roll:-16 Pitch:68 Yaw:38
0 Roll:-15 Pitch:69 Yaw:39
-1 Roll:-16 Pitch:70 Yaw:38
0 Roll:-16 Pitch:71 Yaw:36
-1 Roll:-17 Pitch:72 Yaw:35
0 Roll:-19 Pitch:73 Yaw:32
-1 Roll:-21 Pitch:73 Yaw:30
0 Roll:-21 Pitch:74 Yaw:30
0 Roll:-21 Pitch:75 Yaw:30
0 Roll:-21 Pitch:75 Yaw:30
-1 Roll:-21 Pitch:75 Yaw:28
0 Roll:-22 Pitch:75 Yaw:28
-1 Roll:-23 Pitch:75 Yaw:24
0 Roll:-23 Pitch:75 Yaw:20
-1 Roll:-23 Pitch:74 Yaw:17
1 Roll:-23 Pitch:74 Yaw:13
-1 Roll:-22 Pitch:74 Yaw:10
0 Roll:-23 Pitch:74 Yaw:5
-1 Roll:-23 Pitch:74 Yaw:1
0 Roll:-24 Pitch:74 Yaw:-3
0 Roll:-24 Pitch:74 Yaw:-6
-1 Roll:-24 Pitch:74 Yaw:-10
0 Roll:-24 Pitch:74 Yaw:-13
-1 Roll:-24 Pitch:74 Yaw:-17
0 Roll:-24 Pitch:74 Yaw:-19
-1 Roll:-24 Pitch:74 Yaw:-22
0 Roll:-24 Pitch:74 Yaw:-25
0 Roll:-22 Pitch:74 Yaw:-26
0 Roll:-21 Pitch:74 Yaw:-28
-1 Roll:-19 Pitch:73 Yaw:-28
0 Roll:-15 Pitch:73 Yaw:-27
-1 Roll:-11 Pitch:72 Yaw:-25
0 Roll:-10 Pitch:72 Yaw:-27
-1 Roll:-10 Pitch:72 Yaw:-29
0 Roll:-9 Pitch:71 Yaw:-30
0 Roll:-8 Pitch:70 Yaw:-31
0 Roll:-6 Pitch:68 Yaw:-31
-1 Roll:-1 Pitch:63 Yaw:-28
0 Roll:2 Pitch:57 Yaw:-26
-1 Roll:5 Pitch:51 Yaw:-25
0 Roll:7 Pitch:45 Yaw:-24
-1 Roll:6 Pitch:41 Yaw:-25
0 Roll:8 Pitch:35 Yaw:-25
0 Roll:9 Pitch:32 Yaw:-25
0 Roll:11 Pitch:26 Yaw:-25
-1 Roll:14 Pitch:18 Yaw:-24
0 Roll:17 Pitch:12 Yaw:-25
0 Roll:19 Pitch:7 Yaw:-25
-1 Roll:21 Pitch:3 Yaw:-25
0 Roll:22 Pitch:2 Yaw:-25
-1 Roll:25 Pitch:4 Yaw:-24
0 Roll:31 Pitch:6 Yaw:-23
-1 Roll:36 Pitch:7 Yaw:-23
0 Roll:40 Pitch:7 Yaw:-24
0 Roll:45 Pitch:7 Yaw:-23
-1 Roll:49 Pitch:7 Yaw:-22
0 Roll:54 Pitch:6 Yaw:-22
0 Roll:59 Pitch:4 Yaw:-22
-1 Roll:66 Pitch:3 Yaw:-21
0 Roll:73 Pitch:1 Yaw:-21
-1 Roll:77 Pitch:0 Yaw:-20
0 Roll:80 Pitch:-0 Yaw:-20
1 Roll:83 Pitch:-0 Yaw:-20
-1 Roll:84 Pitch:-1 Yaw:-18
-1 Roll:86 Pitch:-1 Yaw:-18
0 Roll:86 Pitch:-2 Yaw:-17
-1 Roll:87 Pitch:-2 Yaw:-17
0 Roll:88 Pitch:-2 Yaw:-17
0 Roll:89 Pitch:-2 Yaw:-17
-1 Roll:89 Pitch:-2 Yaw:-17
0 Roll:89 Pitch:-2 Yaw:-18
-1 Roll:89 Pitch:-2 Yaw:-18
0 Roll:89 Pitch:-1 Yaw:-19
0 Roll:90 Pitch:-1 Yaw:-19
-1 Roll:90 Pitch:-1 Yaw:-19
0 Roll:90 Pitch:-0 Yaw:-20
0 Roll:90 Pitch:-1 Yaw:-20
-1 Roll:90 Pitch:-0 Yaw:-20
0 Roll:91 Pitch:-0 Yaw:-21
-1 Roll:91 Pitch:-1 Yaw:-21
0 Roll:91 Pitch:-0 Yaw:-21
0 Roll:91 Pitch:-0 Yaw:-22
0 Roll:91 Pitch:-0 Yaw:-22
-1 Roll:90 Pitch:-0 Yaw:-22
0 Roll:90 Pitch:-1 Yaw:-22
0 Roll:90 Pitch:-1 Yaw:-22
-1 Roll:90 Pitch:-1 Yaw:-22
0 Roll:90 Pitch:-1 Yaw:-22
-1 Roll:89 Pitch:-2 Yaw:-23
0 Roll:88 Pitch:-3 Yaw:-24
-1 Roll:86 Pitch:-4 Yaw:-26
0 Roll:85 Pitch:-4 Yaw:-27
0 Roll:84 Pitch:-3 Yaw:-29
-1 Roll:82 Pitch:-3 Yaw:-31
0 Roll:80 Pitch:-3 Yaw:-32
0 Roll:78 Pitch:-3 Yaw:-33
-1 Roll:75 Pitch:-3 Yaw:-34
0 Roll:74 Pitch:-4 Yaw:-33
-1 Roll:74 Pitch:-5 Yaw:-31
0 Roll:71 Pitch:-7 Yaw:-31
0 Roll:68 Pitch:-10 Yaw:-31
-1 Roll:64 Pitch:-13 Yaw:-31
0 Roll:60 Pitch:-17 Yaw:-32
0 Roll:56 Pitch:-20 Yaw:-33
-1 Roll:51 Pitch:-24 Yaw:-36
0 Roll:47 Pitch:-27 Yaw:-37
0 Roll:42 Pitch:-31 Yaw:-39
-1 Roll:36 Pitch:-32 Yaw:-40
0 Roll:30 Pitch:-29 Yaw:-39
-1 Roll:25 Pitch:-28 Yaw:-38
0 Roll:19 Pitch:-27 Yaw:-38
0 Roll:13 Pitch:-23 Yaw:-38
-1 Roll:9 Pitch:-21 Yaw:-37
0 Roll:5 Pitch:-18 Yaw:-36
0 Roll:1 Pitch:-16 Yaw:-35
-1 Roll:-2 Pitch:-16 Yaw:-34
0 Roll:-7 Pitch:-16 Yaw:-34
-1 Roll:-11 Pitch:-15 Yaw:-34

**Comment by PaulZC** [comment]
Hi Manu (@msrivast ),

The DMP is essentially a [black box](https://en.wikipedia.org/wiki/Black_box). We have no information about its inner workings and incomplete information about its registers and settings. It took a huge amount of reverse-engineering to get the SparkFun library to where it is today, and we still don't have the full picture.

Re. 1) I don't think I've ever seen a description of the 20948's internal clock system. Is it surprising that the frequency is a little 'off'? Probably not... Can it be corrected with TIMEBASE_CORRECTION_PLL? Maybe? Do I have any more information about how to set TIMEBASE_CORRECTION_PLL? Nope. Please experiment and let us know what you find. Send us a new example via a [Pull Request](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/main/CONTRIBUTING.md) if possible.

Re. 2) No, sorry, I have no more information on this.

Re. 3) Ditto...

Welcome to the weird and wonderful world of the 20948 DMP!!

Very best wishes,
Paul
