### ISSUE TITLE
getAGMT is very slow (1 ms to complete)

### ISSUE THREAD

**Issue by makeller1** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#98]
### Subject of the issue
The getAGMT() function consistently takes 0.98 ms to complete. 

### Your workbench
* What platform are you using?
  Teensy 4.0
* How is the device wired to your platform?
  I2C
* How is everything being powered?
  Teensy powered through USB. ICM powered through onboard Teensy 3V.

### Steps to reproduce
Running in the main loop:
```
    if(myICM.dataReady() && micros() - last_measurement_us >= MEASUREMENT_RATE)
    {
      double start = micros(); // Start timer
      // Read IMU data (takes 0.98 ms)
      myICM.getAGMT();
      double elapsed_us = micros() - start; // End timer
      last_measurement_us = micros();
    }
```
where MEASUREMENT_RATE =1000 us.

### Expected behaviour
I would expect the process of reading bits to happen in microseconds or less.

### Actual behaviour
It takes 0.98 ms to complete.

**Comment by PaulZC** [comment]
Hi Alexander (@makeller1 ),

Please try SPI instead of I2C.

Best wishes,
Paul
